name: OrquestaApp
favicon: null
layout_spectrum: 0.9001042027957737
typography_spectrum: 0.7844186832662672
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.7487512738443911
  lightness: 0.10515082674100995
  saturation: 0.5839462014846504
  rhythmicContrast: 0.3393293027766049
purpose: []
